# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_hydra_dev.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

# THIS FILE IS FOR ETHAN TO MAKE EDITS

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("KerberosSDR")
        MainWindow.resize(1366, 870)

        self.setStyleSheet("background-color: #041e42; font-family: Manjari;")

        #font = self.font()
        #font.setFamily("Manjari")
        #self.window().setFont(font)
        #self.window().setStyleSheet("font-family: Manjari;")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_6.setSpacing(0)
        self.stackedWidget_config = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_config.setMaximumSize(QtCore.QSize(290, 16777215))
        self.stackedWidget_config.setObjectName("stackedWidget_config")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.doubleSpinBox_center_freq = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_center_freq.setDecimals(4)
        self.doubleSpinBox_center_freq.setMinimum(25.0)
        self.doubleSpinBox_center_freq.setMaximum(2000.0)
        self.doubleSpinBox_center_freq.setProperty("value", 100.0)
        self.doubleSpinBox_center_freq.setObjectName("doubleSpinBox_center_freq")
        self.gridLayout_16.addWidget(self.doubleSpinBox_center_freq, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setObjectName("label_4")
        self.gridLayout_16.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setObjectName("label_3")
        self.gridLayout_16.addWidget(self.label_3, 0, 0, 1, 1)
        
        # added
        self.comboBox_sampling_freq = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_sampling_freq.setObjectName(_fromUtf8("comboBox_sampling_freq"))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.comboBox_sampling_freq.addItem(_fromUtf8(""))
        self.gridLayout_16.addWidget(self.comboBox_sampling_freq, 1, 1, 1, 1)


        self.checkBox_en_uniform_gain = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_en_uniform_gain.setObjectName(_fromUtf8("checkBox_en_uniform_gain"))
        self.gridLayout_16.addWidget(self.checkBox_en_uniform_gain, 2, 0, 1, 1)

        self.label_18 = QtWidgets.QLabel(self.groupBox_7)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_16.addWidget(self.label_18, 3, 0, 1, 1)


        self.label_gain_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_gain_2.setObjectName(_fromUtf8("label_gain_2"))
        self.gridLayout_16.addWidget(self.label_gain_2, 4, 0, 1, 1)


        self.label_gain_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_gain_3.setObjectName(_fromUtf8("label_gain_3"))
        self.gridLayout_16.addWidget(self.label_gain_3, 5, 0, 1, 1)


        self.label_gain_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_gain_4.setObjectName(_fromUtf8("label_gain_4"))
        self.gridLayout_16.addWidget(self.label_gain_4, 6, 0, 1, 1)
        #end
        
        
        # added
        self.comboBox_gain = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_gain.setObjectName(_fromUtf8("comboBox_gain"))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.comboBox_gain.addItem(_fromUtf8(""))
        self.gridLayout_16.addWidget(self.comboBox_gain, 3, 1, 1, 1)

        self.comboBox_gain_2 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_gain_2.setObjectName(_fromUtf8("comboBox_gain_2"))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.comboBox_gain_2.addItem(_fromUtf8(""))
        self.gridLayout_16.addWidget(self.comboBox_gain_2, 4, 1, 1, 1)
        
        self.comboBox_gain_3 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_gain_3.setObjectName(_fromUtf8("comboBox_gain_3"))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.comboBox_gain_3.addItem(_fromUtf8(""))
        self.gridLayout_16.addWidget(self.comboBox_gain_3, 5, 1, 1, 1)
        #end
        
        self.comboBox_gain_4 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_gain_4.setObjectName("comboBox_gain_4")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.comboBox_gain_4.addItem("")
        self.gridLayout_16.addWidget(self.comboBox_gain_4, 6, 1, 1, 1)
        
        
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.pushButton_set_receiver_config = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_set_receiver_config.setObjectName("pushButton_set_receiver_config")
        self.gridLayout_17.addWidget(self.pushButton_set_receiver_config, 1, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.page_4)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_19 = QtWidgets.QLabel(self.groupBox_8)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_8)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_8)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        
        self.label_20 = QtWidgets.QLabel(self.groupBox_8)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 3, 0, 1, 1)
        self.checkBox_en_dc_compensation = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_en_dc_compensation.setText("")
        self.checkBox_en_dc_compensation.setObjectName("checkBox_en_dc_compensation")
        self.gridLayout_2.addWidget(self.checkBox_en_dc_compensation, 0, 1, 1, 1)
        self.doubleSpinBox_filterbw = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.doubleSpinBox_filterbw.setMaximum(3400.0)
        self.doubleSpinBox_filterbw.setProperty("value", 150.0)
        self.doubleSpinBox_filterbw.setObjectName("doubleSpinBox_filterbw")
        self.gridLayout_2.addWidget(self.doubleSpinBox_filterbw, 1, 1, 1, 1)
        self.spinBox_fir_tap_size = QtWidgets.QSpinBox(self.groupBox_8)
        self.spinBox_fir_tap_size.setMaximum(10000)
        self.spinBox_fir_tap_size.setObjectName("spinBox_fir_tap_size")
        self.gridLayout_2.addWidget(self.spinBox_fir_tap_size, 2, 1, 1, 1)
        self.spinBox_decimation = QtWidgets.QSpinBox(self.groupBox_8)
        self.spinBox_decimation.setMinimum(1)
        self.spinBox_decimation.setMaximum(1000)
        self.spinBox_decimation.setObjectName("spinBox_decimation")
        self.gridLayout_2.addWidget(self.spinBox_decimation, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_8)

        self.checkBox_en_spectrum = QtWidgets.QCheckBox(self.page_4)
        self.checkBox_en_spectrum.setObjectName("checkBox_en_spectrum")
        self.verticalLayout_7.addWidget(self.checkBox_en_spectrum)
        self.stackedWidget_config.addWidget(self.page_4)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 0, 0, 1, 1)
        
        
        
        self.checkBox_en_sync_display = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_en_sync_display.setText("")
        self.checkBox_en_sync_display.setObjectName("checkBox_en_sync_display")
        self.gridLayout_8.addWidget(self.checkBox_en_sync_display, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        self.label_32.setObjectName("label_32")
        self.gridLayout_8.addWidget(self.label_32, 1, 0, 1, 1)
        self.checkBox_en_noise_source = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_en_noise_source.setText("")
        self.checkBox_en_noise_source.setObjectName("checkBox_en_noise_source")
        self.gridLayout_8.addWidget(self.checkBox_en_noise_source, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_8)
        self.pushButton_del_sync_history = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_del_sync_history.setObjectName("pushButton_del_sync_history")
        self.verticalLayout_2.addWidget(self.pushButton_del_sync_history)
        self.pushButton_sync = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_sync.setObjectName("pushButton_sync")
        self.verticalLayout_2.addWidget(self.pushButton_sync)
        self.pushButton_iq_calib = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_iq_calib.setObjectName("pushButton_iq_calib")
        self.verticalLayout_2.addWidget(self.pushButton_iq_calib)
        
        # added
        # Add Resync Time Control Box
        self.label_resync_time = QtWidgets.QLabel(self.groupBox)
        self.label_resync_time.setObjectName(_fromUtf8("label_resync_time"))
        self.gridLayout_8.addWidget(self.label_resync_time, 2, 0, 1, 1)

        self.spinBox_resync_time = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_resync_time.setObjectName(_fromUtf8("spinBox_resync_time"))
        self.spinBox_resync_time.setMinimum(0)
        self.spinBox_resync_time.setMaximum(99999)

        self.gridLayout_8.addWidget(self.spinBox_resync_time, 2, 1, 1, 1)
        #end
        
        self.gridLayout_9.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        
        
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.stackedWidget_config.addWidget(self.page)
        #DOA Stuff?
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 1, 0, 1, 1)
        self.comboBox_antenna_alignment = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_antenna_alignment.setObjectName("comboBox_antenna_alignment")
        self.comboBox_antenna_alignment.addItem("")
        self.comboBox_antenna_alignment.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_antenna_alignment, 0, 1, 1, 1)
        self.doubleSpinBox_DOA_d = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_DOA_d.setDecimals(4)
        self.doubleSpinBox_DOA_d.setProperty("value", 0.5)
        self.doubleSpinBox_DOA_d.setObjectName("doubleSpinBox_DOA_d")
        self.gridLayout_4.addWidget(self.doubleSpinBox_DOA_d, 1, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        #self.pushButton_DOA_cal_90 = QtWidgets.QPushButton(self.groupBox_2)
        #self.pushButton_DOA_cal_90.setObjectName("pushButton_DOA_cal_90")
        #self.gridLayout_7.addWidget(self.pushButton_DOA_cal_90, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        #self.checkBox_en_DOA_MEM = QtWidgets.QCheckBox(self.groupBox_4)
        #self.checkBox_en_DOA_MEM.setText("")
        #self.checkBox_en_DOA_MEM.setObjectName("checkBox_en_DOA_MEM")
        #self.gridLayout.addWidget(self.checkBox_en_DOA_MEM, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)

        # Phase Shifter Enable/Disable - RED
        self.checkBox_en_PhaseShifter = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_en_PhaseShifter.setObjectName(_fromUtf8("checkBox_en_PhaseShifter"))
        self.gridLayout_7.addWidget(self.checkBox_en_PhaseShifter,2,0,1,1)

        #self.checkBox_en_DOA_Bartlett = QtWidgets.QCheckBox(self.groupBox_4)
        #self.checkBox_en_DOA_Bartlett.setText("")
        #self.checkBox_en_DOA_Bartlett.setObjectName("checkBox_en_DOA_Bartlett")
        #self.gridLayout.addWidget(self.checkBox_en_DOA_Bartlett, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        #self.checkBox_en_DOA_Capon = QtWidgets.QCheckBox(self.groupBox_4)
        #self.checkBox_en_DOA_Capon.setText("")
        #self.checkBox_en_DOA_Capon.setObjectName("checkBox_en_DOA_Capon")
        #self.gridLayout.addWidget(self.checkBox_en_DOA_Capon, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        #self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        #self.label_8.setObjectName("label_8")
        #self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.spinBox_DOA_sample_size = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_DOA_sample_size.setMinimum(1)
        self.spinBox_DOA_sample_size.setMaximum(22)
        self.spinBox_DOA_sample_size.setProperty("value", 15)
        self.spinBox_DOA_sample_size.setObjectName("spinBox_DOA_sample_size")
        self.gridLayout.addWidget(self.spinBox_DOA_sample_size, 4, 1, 1, 1)
        self.checkBox_en_DOA_MUSIC = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA_MUSIC.setText("")
        self.checkBox_en_DOA_MUSIC.setObjectName("checkBox_en_DOA_MUSIC")
        self.gridLayout.addWidget(self.checkBox_en_DOA_MUSIC, 2, 1, 1, 1)
        self.checkBox_en_DOA = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA.setText("")
        self.checkBox_en_DOA.setChecked(True)
        self.checkBox_en_DOA.setObjectName("checkBox_en_DOA")
        self.gridLayout.addWidget(self.checkBox_en_DOA, 0, 1, 1, 1)
        #self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        #self.label_7.setObjectName("label_7")
        #self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        #elf.label_6 = QtWidgets.QLabel(self.groupBox_4)
        #self.label_6.setObjectName("label_6")
        #self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        
        # fb-alg
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 5, 0, 1, 1)
        self.checkBox_en_DOA_FB_avg = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_en_DOA_FB_avg.setText("")
        self.checkBox_en_DOA_FB_avg.setObjectName("checkBox_en_DOA_FB_avg")
        self.gridLayout.addWidget(self.checkBox_en_DOA_FB_avg, 5, 1, 1, 1)

        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)

        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)

        # init delta labels -EDT
        self.label_delta = QtWidgets.QLabel(self.groupBox_4)
        self.label_delta.setObjectName("label_delta")
        self.gridLayout.addWidget(self.label_delta, 8, 0, 1, 1)

        self.label_delta_value = QtWidgets.QLabel(self.groupBox_4)
        self.label_delta_value.setObjectName("label_delta_value")
        self.gridLayout.addWidget(self.label_delta_value, 8, 1, 1, 1)

        #init DOA angle labels -EDT
        self.label_DOA = QtWidgets.QLabel(self.groupBox_4)
        self.label_DOA.setObjectName("label_DOA")
        self.gridLayout.addWidget(self.label_DOA, 9, 0, 1, 1)

        self.label_DOA_value = QtWidgets.QLabel(self.groupBox_4)
        self.label_DOA_value.setObjectName("label_DOA_value")
        self.gridLayout.addWidget(self.label_DOA_value, 9, 1, 1, 1)

        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.stackedWidget_config.addWidget(self.page_2)
        #end?
        self.verticalLayout_6.addWidget(self.stackedWidget_config)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setMaximumSize(QtCore.QSize(290, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")

        # add Artemis logo
        self.label_artemis = QtWidgets.QLabel(self.groupBox_6)
        self.label_artemis.setGeometry(QtCore.QRect(45,145,200, 200))
        self.pixmap = QPixmap('Artemis_Logo.png')
        self.label_artemis.setScaledContents(True)
        self.label_artemis.setPixmap(self.pixmap)
        self.show()

        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_power_level = QtWidgets.QLabel(self.groupBox_6)
        self.label_power_level.setObjectName("label_power_level")
        self.gridLayout_14.addWidget(self.label_power_level, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setObjectName("label_17")
        self.gridLayout_14.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_update_rate = QtWidgets.QLabel(self.groupBox_6)
        self.label_update_rate.setObjectName("label_update_rate")
        self.gridLayout_14.addWidget(self.label_update_rate, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setObjectName("label_22")
        self.gridLayout_14.addWidget(self.label_22, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 2, 0, 1, 1)

        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem1, 5, 0, 1, 1)
        self.pushButton_close = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout_15.addWidget(self.pushButton_close, 4, 0, 1, 1)
        self.pushButton_proc_control = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_proc_control.setObjectName("pushButton_proc_control")
        self.gridLayout_15.addWidget(self.pushButton_proc_control, 3, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Manjari")
        
        self.tabWidget.setStyleSheet("""
                        border-radius: 8px; 
                        color: white;
                        """)
        #self.tabWidget.setStyleSheet("border-radius: 10px")
        #self.tabWidget.setStyleSheet()
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_spectrum = QtWidgets.QWidget()
        palette = QtGui.QPalette()
        self.tab_spectrum.setPalette(palette)
        self.tab_spectrum.setObjectName("tab_spectrum")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_spectrum)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_spectrum = QtWidgets.QGridLayout()
        self.gridLayout_spectrum.setObjectName("gridLayout_spectrum")
        self.gridLayout_6.addLayout(self.gridLayout_spectrum, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_spectrum, "")
        self.tab_symc = QtWidgets.QWidget()
        self.tab_symc.setObjectName("tab_symc")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_symc)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_sync = QtWidgets.QGridLayout()
        self.gridLayout_sync.setObjectName("gridLayout_sync")
        self.gridLayout_5.addLayout(self.gridLayout_sync, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_symc, "")

        # add DoA
        self.tab_DOA = QtWidgets.QWidget()
        self.tab_DOA.setObjectName("tab_DOA")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_DOA)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_DOA = QtWidgets.QGridLayout()
        self.gridLayout_DOA.setObjectName("gridLayout_DOA")
        self.gridLayout_12.addLayout(self.gridLayout_DOA, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_DOA, "")
        #end

        # coloring scheme
        customP = self.palette()
        customP.setColor(self.tab_DOA.backgroundRole(), QtCore.Qt.white)
        #self.groupBox_7.setStyleSheet("background-color: #d6d6d6;")
        #self.groupBox_8.setStyleSheet("background-color: #d6d6d6;")
        self.page.setStyleSheet("background-color: #d5e5f2;")
        self.page_2.setStyleSheet("background-color: #d5e5f2;")
        self.page_4.setStyleSheet("background-color: #d5e5f2;")
        self.tab_DOA.setStyleSheet("background-color: white;")
        self.tab_symc.setStyleSheet("background-color: white;")
        self.tab_spectrum.setStyleSheet("background-color: white;")
        self.groupBox_6.setStyleSheet("background-color: #d5e5f2;")
        self.tab_DOA.setPalette(customP)

        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_config.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
    	# added start
        MainWindow.setWindowTitle(_translate("KerberosSDR", "Artemis Tracking Software", None))
        self.groupBox_7.setTitle(_translate("KerberosSDR", "Receiver configaration", None))
        self.label_4.setText(_translate("KerberosSDR", "Sampling frequency [MHz]:", None))
        self.comboBox_sampling_freq.setItemText(0, _translate("KerberosSDR", "0.25", None))
        self.comboBox_sampling_freq.setItemText(1, _translate("KerberosSDR", "0.900001", None))
        self.comboBox_sampling_freq.setItemText(2, _translate("KerberosSDR", "1.024", None))
        self.comboBox_sampling_freq.setItemText(3, _translate("KerberosSDR", "1.4", None))
        self.comboBox_sampling_freq.setItemText(4, _translate("KerberosSDR", "1.8", None))
        self.comboBox_sampling_freq.setItemText(5, _translate("KerberosSDR", "1.92", None))
        self.comboBox_sampling_freq.setItemText(6, _translate("KerberosSDR", "2.048", None))
        self.comboBox_sampling_freq.setItemText(7, _translate("KerberosSDR", "2.4", None))
        self.comboBox_sampling_freq.setItemText(8, _translate("KerberosSDR", "2.56", None))
        self.comboBox_sampling_freq.setCurrentIndex(2)

        self.checkBox_en_uniform_gain.setText(_translate("MainWindow", "Uniform Gain", None))

        self.checkBox_en_PhaseShifter.setText(_translate("MainWindow", "Analog Beamforming", None)) # Phase shifter - RED

        self.label_3.setText(_translate("KerberosSDR", "Center frequency [MHz]:", None))
        self.label_18.setText(_translate("KerberosSDR", "RX1 Gain [dB]:", None))
        self.comboBox_gain.setItemText(0, _translate("KerberosSDR", "0", None))
        self.comboBox_gain.setItemText(1, _translate("KerberosSDR", "0.9", None))
        self.comboBox_gain.setItemText(2, _translate("KerberosSDR", "1.4", None))
        self.comboBox_gain.setItemText(3, _translate("KerberosSDR", "2.7", None))
        self.comboBox_gain.setItemText(4, _translate("KerberosSDR", "3.7", None))
        self.comboBox_gain.setItemText(5, _translate("KerberosSDR", "7.7", None))
        self.comboBox_gain.setItemText(6, _translate("KerberosSDR", "8.7", None))
        self.comboBox_gain.setItemText(7, _translate("KerberosSDR", "12.5", None))
        self.comboBox_gain.setItemText(8, _translate("KerberosSDR", "14.4", None))
        self.comboBox_gain.setItemText(9, _translate("KerberosSDR", "15.7", None))
        self.comboBox_gain.setItemText(10, _translate("KerberosSDR", "16.6", None))
        self.comboBox_gain.setItemText(11, _translate("KerberosSDR", "19.7", None))
        self.comboBox_gain.setItemText(12, _translate("KerberosSDR", "20.7", None))
        self.comboBox_gain.setItemText(13, _translate("KerberosSDR", "22.9", None))
        self.comboBox_gain.setItemText(14, _translate("KerberosSDR", "25.4", None))
        self.comboBox_gain.setItemText(15, _translate("KerberosSDR", "28.0", None))
        self.comboBox_gain.setItemText(16, _translate("KerberosSDR", "29.7", None))
        self.comboBox_gain.setItemText(17, _translate("KerberosSDR", "32.8", None))
        self.comboBox_gain.setItemText(18, _translate("KerberosSDR", "33.8", None))
        self.comboBox_gain.setItemText(19, _translate("KerberosSDR", "36.4", None))
        self.comboBox_gain.setItemText(20, _translate("KerberosSDR", "37.2", None))
        self.comboBox_gain.setItemText(21, _translate("KerberosSDR", "38.6", None))
        self.comboBox_gain.setItemText(22, _translate("KerberosSDR", "40.2", None))
        self.comboBox_gain.setItemText(23, _translate("KerberosSDR", "42.1", None))
        self.comboBox_gain.setItemText(24, _translate("KerberosSDR", "43.4", None))
        self.comboBox_gain.setItemText(25, _translate("KerberosSDR", "43.9", None))
        self.comboBox_gain.setItemText(26, _translate("KerberosSDR", "44.5", None))
        self.comboBox_gain.setItemText(27, _translate("KerberosSDR", "48.0", None))
        self.comboBox_gain.setItemText(28, _translate("KerberosSDR", "49.6", None))

        self.label_gain_2.setText(_translate("KerberosSDR", "RX2 Gain [dB]:", None))
        self.comboBox_gain_2.setItemText(0, _translate("KerberosSDR", "0", None))
        self.comboBox_gain_2.setItemText(1, _translate("KerberosSDR", "0.9", None))
        self.comboBox_gain_2.setItemText(2, _translate("KerberosSDR", "1.4", None))
        self.comboBox_gain_2.setItemText(3, _translate("KerberosSDR", "2.7", None))
        self.comboBox_gain_2.setItemText(4, _translate("KerberosSDR", "3.7", None))
        self.comboBox_gain_2.setItemText(5, _translate("KerberosSDR", "7.7", None))
        self.comboBox_gain_2.setItemText(6, _translate("KerberosSDR", "8.7", None))
        self.comboBox_gain_2.setItemText(7, _translate("KerberosSDR", "12.5", None))
        self.comboBox_gain_2.setItemText(8, _translate("KerberosSDR", "14.4", None))
        self.comboBox_gain_2.setItemText(9, _translate("KerberosSDR", "15.7", None))
        self.comboBox_gain_2.setItemText(10, _translate("KerberosSDR", "16.6", None))
        self.comboBox_gain_2.setItemText(11, _translate("KerberosSDR", "19.7", None))
        self.comboBox_gain_2.setItemText(12, _translate("KerberosSDR", "20.7", None))
        self.comboBox_gain_2.setItemText(13, _translate("KerberosSDR", "22.9", None))
        self.comboBox_gain_2.setItemText(14, _translate("KerberosSDR", "25.4", None))
        self.comboBox_gain_2.setItemText(15, _translate("KerberosSDR", "28.0", None))
        self.comboBox_gain_2.setItemText(16, _translate("KerberosSDR", "29.7", None))
        self.comboBox_gain_2.setItemText(17, _translate("KerberosSDR", "32.8", None))
        self.comboBox_gain_2.setItemText(18, _translate("KerberosSDR", "33.8", None))
        self.comboBox_gain_2.setItemText(19, _translate("KerberosSDR", "36.4", None))
        self.comboBox_gain_2.setItemText(20, _translate("KerberosSDR", "37.2", None))
        self.comboBox_gain_2.setItemText(21, _translate("KerberosSDR", "38.6", None))
        self.comboBox_gain_2.setItemText(22, _translate("KerberosSDR", "40.2", None))
        self.comboBox_gain_2.setItemText(23, _translate("KerberosSDR", "42.1", None))
        self.comboBox_gain_2.setItemText(24, _translate("KerberosSDR", "43.4", None))
        self.comboBox_gain_2.setItemText(25, _translate("KerberosSDR", "43.9", None))
        self.comboBox_gain_2.setItemText(26, _translate("KerberosSDR", "44.5", None))
        self.comboBox_gain_2.setItemText(27, _translate("KerberosSDR", "48.0", None))
        self.comboBox_gain_2.setItemText(28, _translate("KerberosSDR", "49.6", None))


        self.label_gain_3.setText(_translate("KerberosSDR", "RX3 Gain [dB]:", None))
        self.comboBox_gain_3.setItemText(0, _translate("KerberosSDR", "0", None))
        self.comboBox_gain_3.setItemText(1, _translate("KerberosSDR", "0.9", None))
        self.comboBox_gain_3.setItemText(2, _translate("KerberosSDR", "1.4", None))
        self.comboBox_gain_3.setItemText(3, _translate("KerberosSDR", "2.7", None))
        self.comboBox_gain_3.setItemText(4, _translate("KerberosSDR", "3.7", None))
        self.comboBox_gain_3.setItemText(5, _translate("KerberosSDR", "7.7", None))
        self.comboBox_gain_3.setItemText(6, _translate("KerberosSDR", "8.7", None))
        self.comboBox_gain_3.setItemText(7, _translate("KerberosSDR", "12.5", None))
        self.comboBox_gain_3.setItemText(8, _translate("KerberosSDR", "14.4", None))
        self.comboBox_gain_3.setItemText(9, _translate("KerberosSDR", "15.7", None))
        self.comboBox_gain_3.setItemText(10, _translate("KerberosSDR", "16.6", None))
        self.comboBox_gain_3.setItemText(11, _translate("KerberosSDR", "19.7", None))
        self.comboBox_gain_3.setItemText(12, _translate("KerberosSDR", "20.7", None))
        self.comboBox_gain_3.setItemText(13, _translate("KerberosSDR", "22.9", None))
        self.comboBox_gain_3.setItemText(14, _translate("KerberosSDR", "25.4", None))
        self.comboBox_gain_3.setItemText(15, _translate("KerberosSDR", "28.0", None))
        self.comboBox_gain_3.setItemText(16, _translate("KerberosSDR", "29.7", None))
        self.comboBox_gain_3.setItemText(17, _translate("KerberosSDR", "32.8", None))
        self.comboBox_gain_3.setItemText(18, _translate("KerberosSDR", "33.8", None))
        self.comboBox_gain_3.setItemText(19, _translate("KerberosSDR", "36.4", None))
        self.comboBox_gain_3.setItemText(20, _translate("KerberosSDR", "37.2", None))
        self.comboBox_gain_3.setItemText(21, _translate("KerberosSDR", "38.6", None))
        self.comboBox_gain_3.setItemText(22, _translate("KerberosSDR", "40.2", None))
        self.comboBox_gain_3.setItemText(23, _translate("KerberosSDR", "42.1", None))
        self.comboBox_gain_3.setItemText(24, _translate("KerberosSDR", "43.4", None))
        self.comboBox_gain_3.setItemText(25, _translate("KerberosSDR", "43.9", None))
        self.comboBox_gain_3.setItemText(26, _translate("KerberosSDR", "44.5", None))
        self.comboBox_gain_3.setItemText(27, _translate("KerberosSDR", "48.0", None))
        self.comboBox_gain_3.setItemText(28, _translate("KerberosSDR", "49.6", None))

        self.label_gain_4.setText(_translate("KerberosSDR", "RX4 Gain [dB]:", None))
        self.comboBox_gain_4.setItemText(0, _translate("KerberosSDR", "0", None))
        self.comboBox_gain_4.setItemText(1, _translate("KerberosSDR", "0.9", None))
        self.comboBox_gain_4.setItemText(2, _translate("KerberosSDR", "1.4", None))
        self.comboBox_gain_4.setItemText(3, _translate("KerberosSDR", "2.7", None))
        self.comboBox_gain_4.setItemText(4, _translate("KerberosSDR", "3.7", None))
        self.comboBox_gain_4.setItemText(5, _translate("KerberosSDR", "7.7", None))
        self.comboBox_gain_4.setItemText(6, _translate("KerberosSDR", "8.7", None))
        self.comboBox_gain_4.setItemText(7, _translate("KerberosSDR", "12.5", None))
        self.comboBox_gain_4.setItemText(8, _translate("KerberosSDR", "14.4", None))
        self.comboBox_gain_4.setItemText(9, _translate("KerberosSDR", "15.7", None))
        self.comboBox_gain_4.setItemText(10, _translate("KerberosSDR", "16.6", None))
        self.comboBox_gain_4.setItemText(11, _translate("KerberosSDR", "19.7", None))
        self.comboBox_gain_4.setItemText(12, _translate("KerberosSDR", "20.7", None))
        self.comboBox_gain_4.setItemText(13, _translate("KerberosSDR", "22.9", None))
        self.comboBox_gain_4.setItemText(14, _translate("KerberosSDR", "25.4", None))
        self.comboBox_gain_4.setItemText(15, _translate("KerberosSDR", "28.0", None))
        self.comboBox_gain_4.setItemText(16, _translate("KerberosSDR", "29.7", None))
        self.comboBox_gain_4.setItemText(17, _translate("KerberosSDR", "32.8", None))
        self.comboBox_gain_4.setItemText(18, _translate("KerberosSDR", "33.8", None))
        self.comboBox_gain_4.setItemText(19, _translate("KerberosSDR", "36.4", None))
        self.comboBox_gain_4.setItemText(20, _translate("KerberosSDR", "37.2", None))
        self.comboBox_gain_4.setItemText(21, _translate("KerberosSDR", "38.6", None))
        self.comboBox_gain_4.setItemText(22, _translate("KerberosSDR", "40.2", None))
        self.comboBox_gain_4.setItemText(23, _translate("KerberosSDR", "42.1", None))
        self.comboBox_gain_4.setItemText(24, _translate("KerberosSDR", "43.4", None))
        self.comboBox_gain_4.setItemText(25, _translate("KerberosSDR", "43.9", None))
        self.comboBox_gain_4.setItemText(26, _translate("KerberosSDR", "44.5", None))
        self.comboBox_gain_4.setItemText(27, _translate("KerberosSDR", "48.0", None))
        self.comboBox_gain_4.setItemText(28, _translate("KerberosSDR", "49.6", None))
	# added end
	
        self.pushButton_set_receiver_config.setText(_translate("KerberosSDR", "Set", None))
        self.groupBox_8.setTitle(_translate("KerberosSDR", "IQ preprocessing", None))
        self.label_19.setText(_translate("KerberosSDR", "FIR tap size:", None))
        self.label_2.setText(_translate("KerberosSDR", "Filter BW [kHz]: ", None))
        self.label.setText(_translate("KerberosSDR", "DC compensation:", None))
        self.label_20.setText(_translate("KerberosSDR", "Decimation:", None))
        self.spinBox_fir_tap_size.setToolTip(_translate("KerberosSDR", "<html><head/><body><p>Set to 0 to disable FIR filtering.</p></body></html>", None))
        self.checkBox_en_spectrum.setText(_translate("KerberosSDR", "Enable spectrum display", None))
        self.groupBox.setTitle(_translate("KerberosSDR", "Syncronization", None))
        self.label_12.setText(_translate("KerberosSDR", "Enable sync display:", None))
        self.label_32.setText(_translate("KerberosSDR", "Noise source ON/OFF", None))
        self.pushButton_del_sync_history.setText(_translate("KerberosSDR", "Delete history", None))
        self.pushButton_sync.setText(_translate("KerberosSDR", "Sample sync", None))
        self.pushButton_iq_calib.setText(_translate("KerberosSDR", "Calibrate IQ", None))
        self.groupBox_6.setTitle(_translate("KerberosSDR", "Status ", None))
        self.label_power_level.setText(_translate("KerberosSDR", "OK", None))
        self.label_17.setText(_translate("KerberosSDR", "Powel level:", None))
        self.label_update_rate.setText(_translate("KerberosSDR", "-ms", None))
        self.label_22.setText(_translate("KerberosSDR", "Update rate:", None))
        self.pushButton_close.setText(_translate("KerberosSDR", "Exit", None))
        self.pushButton_proc_control.setText(_translate("KerberosSDR", "Start processing", None))
        #Added DoA
        self.groupBox_2.setTitle(_translate("KerberosSDR", "Antenna configuration", None))
        self.label_21.setText(_translate("KerberosSDR", "Arrangement:", None))
        self.label_24.setText(_translate("KerberosSDR", "Spacing [meters]:", None))
        self.comboBox_antenna_alignment.setToolTip(_translate("KerberosSDR", "<html><head/><body><p>ULA (Uniform Linear Array)<br/>UCA (Uniform Ciruclar Array)</p></body></html>", None))
        self.comboBox_antenna_alignment.setItemText(0, _translate("KerberosSDR", "ULA", None))
        self.comboBox_antenna_alignment.setItemText(1, _translate("KerberosSDR", "UCA", None))
        #self.pushButton_DOA_cal_90.setText(_translate("KerberosSDR", "Calibrate 90 deg", None))
        self.groupBox_4.setTitle(_translate("KerberosSDR", "DOA estimation", None))
        self.label_10.setText(_translate("KerberosSDR", "Sample size 2^x:", None))
        self.label_11.setText(_translate("KerberosSDR", "Enable/Disable:", None))
        self.label_9.setText(_translate("KerberosSDR", "Enable/Disable", None))
        #self.label_8.setText(_translate("KerberosSDR", "MEM", None))
        #self.label_7.setText(_translate("KerberosSDR", "Capon", None))
        #self.label_6.setText(_translate("KerberosSDR", "Bartlett", None))
        self.label_16.setText(_translate("KerberosSDR", "FB average:", None))
        self.label_5.setText(_translate("KerberosSDR", "MUSIC Algorithm", None))
        self.label_7.setText(_translate("KerberosSDR", "Phase Shift", None))
        self.label_15.setText(_translate("KerberosSDR", "Corr. matrix", None))

        # delta display -EDT
        self.label_delta.setText(_translate("KerberosSDR", "Delta:", None))
        self.label_delta_value.setText(_translate("KerberosSDR", "degrees", None))
        # DOA angle display
        self.label_DOA.setText(_translate("KerberosSDR", "DOA Angle:", None))
        self.label_DOA_value.setText(_translate("KerberosSDR", "degrees", None))

        #end DoA
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_spectrum), _translate("KerberosSDR", "Configuration and Spectrum", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_symc), _translate("KerberosSDR", "Sync", None))

        # add DoA stuff
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_DOA), _translate("KerberosSDR", "DOA Estimation", None))


'''
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
'''
